"""add_project_languages_table

Revision ID: 6b036f40425a
Revises: 1e02ad902d11
Create Date: 2026-01-29 15:35:09.741283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b036f40425a'
down_revision = '1e02ad902d11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###






