"""add project_management_metrics table

Revision ID: 90a71996ac03
Revises: 5f6a7b8c9d0e
Create Date: 2026-03-17 22:58:25.761954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90a71996ac03'
down_revision = '5f6a7b8c9d0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_management_metrics',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('archive_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('archive_original_filename', sa.String(), nullable=True),
    sa.Column('archive_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('running_tasks', sa.Integer(), nullable=True),
    sa.Column('audit_tasks', sa.Integer(), nullable=True),
    sa.Column('agent_tasks', sa.Integer(), nullable=True),
    sa.Column('opengrep_tasks', sa.Integer(), nullable=True),
    sa.Column('gitleaks_tasks', sa.Integer(), nullable=True),
    sa.Column('bandit_tasks', sa.Integer(), nullable=True),
    sa.Column('phpstan_tasks', sa.Integer(), nullable=True),
    sa.Column('critical', sa.Integer(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('last_completed_task_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.drop_index(op.f('ix_agent_findings_confidence'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_reachability'), table_name='agent_findings')
    op.alter_column('bandit_findings', 'test_id',
               existing_type=sa.VARCHAR(),
               comment='Bandit 规则ID，例如 B602',
               existing_nullable=False)
    op.alter_column('bandit_findings', 'test_name',
               existing_type=sa.VARCHAR(),
               comment='Bandit 规则名称',
               existing_nullable=False)
    op.alter_column('bandit_findings', 'issue_severity',
               existing_type=sa.VARCHAR(),
               comment='HIGH, MEDIUM, LOW',
               existing_nullable=False)
    op.alter_column('bandit_findings', 'issue_confidence',
               existing_type=sa.VARCHAR(),
               comment='HIGH, MEDIUM, LOW',
               existing_nullable=False)
    op.alter_column('bandit_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='open, verified, false_positive, fixed',
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_index(op.f('ix_bandit_findings_scan_task_status_created'), table_name='bandit_findings')
    op.create_index('ix_bandit_findings_scan_task_status_created', 'bandit_findings', ['scan_task_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('bandit_rule_states', 'test_id',
               existing_type=sa.VARCHAR(),
               comment='Bandit 规则ID，例如 B602',
               existing_nullable=False)
    op.alter_column('bandit_rule_states', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='规则是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('bandit_rule_states', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='规则是否软删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('bandit_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='pending, running, completed, failed, interrupted',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bandit_scan_tasks', 'target_path',
               existing_type=sa.VARCHAR(),
               comment='扫描目标路径',
               existing_nullable=False)
    op.alter_column('bandit_scan_tasks', 'severity_level',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='low, medium, high',
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('bandit_scan_tasks', 'confidence_level',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='low, medium, high',
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('bandit_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='发现总数',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'high_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='HIGH 严重度数量',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'medium_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='MEDIUM 严重度数量',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'low_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='LOW 严重度数量',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='扫描耗时(毫秒)',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='扫描文件数',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment='失败/中断错误信息',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'rule_id',
               existing_type=sa.VARCHAR(),
               comment='规则 ID (如 aws-access-token)',
               existing_nullable=False)
    op.alter_column('gitleaks_findings', 'description',
               existing_type=sa.TEXT(),
               comment='密钥描述',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'file_path',
               existing_type=sa.VARCHAR(),
               comment='文件路径',
               existing_nullable=False)
    op.alter_column('gitleaks_findings', 'start_line',
               existing_type=sa.INTEGER(),
               comment='起始行号',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'end_line',
               existing_type=sa.INTEGER(),
               comment='结束行号',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'secret',
               existing_type=sa.TEXT(),
               comment='密钥内容(已脱敏)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'match',
               existing_type=sa.TEXT(),
               comment='匹配的完整文本',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'commit',
               existing_type=sa.VARCHAR(),
               comment='Git commit SHA (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'author',
               existing_type=sa.VARCHAR(),
               comment='作者 (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'email',
               existing_type=sa.VARCHAR(),
               comment='邮箱 (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'date',
               existing_type=sa.VARCHAR(),
               comment='日期 (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'fingerprint',
               existing_type=sa.VARCHAR(),
               comment='Gitleaks 指纹',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='open, verified, false_positive, fixed',
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('gitleaks_rules', 'rule_id',
               existing_type=sa.VARCHAR(),
               comment='gitleaks 规则 ID',
               existing_nullable=False)
    op.alter_column('gitleaks_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='pending, running, completed, failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('gitleaks_scan_tasks', 'target_path',
               existing_type=sa.VARCHAR(),
               comment='扫描的目标路径',
               existing_nullable=False)
    op.alter_column('gitleaks_scan_tasks', 'no_git',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='是否不使用 git history',
               existing_server_default=sa.text("'true'::character varying"))
    op.alter_column('gitleaks_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='发现的密钥泄露总数',
               existing_server_default=sa.text('0'))
    op.alter_column('gitleaks_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='扫描耗时(毫秒)',
               existing_server_default=sa.text('0'))
    op.alter_column('gitleaks_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='已扫描文件数',
               existing_server_default=sa.text('0'))
    op.alter_column('gitleaks_scan_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('opengrep_findings', 'rule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('opengrep_findings', 'description',
               existing_type=sa.TEXT(),
               comment='漏洞描述',
               existing_nullable=True)
    op.alter_column('opengrep_findings', 'severity',
               existing_type=sa.VARCHAR(),
               comment='ERROR, WARNING, INFO',
               existing_nullable=False)
    op.alter_column('opengrep_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='open, verified, false_positive',
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('opengrep_rules', 'severity',
               existing_type=sa.VARCHAR(),
               comment='ERROR, WARNING, INFO',
               existing_nullable=False)
    op.alter_column('opengrep_rules', 'confidence',
               existing_type=sa.VARCHAR(),
               comment='置信度: HIGH, MEDIUM, LOW',
               existing_nullable=True)
    op.alter_column('opengrep_rules', 'description',
               existing_type=sa.TEXT(),
               comment='规则描述，对应YAML中的message字段',
               existing_nullable=True)
    op.alter_column('opengrep_rules', 'cwe',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='CWE列表，对应YAML中的cwe字段',
               existing_nullable=True)
    op.alter_column('opengrep_rules', 'source',
               existing_type=sa.VARCHAR(),
               comment='internal, patch, json',
               existing_nullable=False)
    op.alter_column('opengrep_rules', 'correct',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否是正确的语法',
               existing_server_default=sa.text('false'))
    op.alter_column('opengrep_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否启用',
               existing_server_default=sa.text('true'))
    op.alter_column('opengrep_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='pending, running, completed, failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('opengrep_scan_tasks', 'rulesets',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               comment='应用的规则集列表',
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('opengrep_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'warning_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'lines_scanned',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('phpstan_rule_states', 'rule_id',
               existing_type=sa.VARCHAR(),
               comment='规则唯一键',
               existing_nullable=False)
    op.alter_column('phpstan_rule_states', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='规则是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('phpstan_rule_states', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='规则是否软删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('project_info', 'language_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='项目所用编程语言信息, JSON格式',
               existing_nullable=True)
    op.alter_column('project_info', 'description',
               existing_type=sa.VARCHAR(),
               comment='项目描述, 由大模型生成',
               existing_nullable=True)
    op.alter_column('project_info', 'status',
               existing_type=sa.VARCHAR(),
               comment='信息状态: pending, completed, failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('project_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_project_info_project_id'), table_name='project_info')
    op.alter_column('yasa_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='open, verified, false_positive, fixed',
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_constraint(op.f('yasa_findings_scan_task_id_fkey'), 'yasa_findings', type_='foreignkey')
    op.create_foreign_key(None, 'yasa_findings', 'yasa_scan_tasks', ['scan_task_id'], ['id'])
    op.alter_column('yasa_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='pending, running, completed, failed, interrupted',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('yasa_scan_tasks', 'target_path',
               existing_type=sa.VARCHAR(),
               comment='扫描目标路径',
               existing_nullable=False)
    op.alter_column('yasa_scan_tasks', 'checker_pack_ids',
               existing_type=sa.VARCHAR(),
               comment='逗号分隔 checker pack',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'checker_ids',
               existing_type=sa.TEXT(),
               comment='逗号分隔 checker id',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'rule_config_file',
               existing_type=sa.VARCHAR(),
               comment='rule config 文件路径',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='发现总数',
               existing_server_default=sa.text('0'))
    op.alter_column('yasa_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='扫描耗时(毫秒)',
               existing_server_default=sa.text('0'))
    op.alter_column('yasa_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='扫描文件数',
               existing_server_default=sa.text('0'))
    op.alter_column('yasa_scan_tasks', 'diagnostics_summary',
               existing_type=sa.TEXT(),
               comment='诊断日志摘要',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment='失败/中断错误信息',
               existing_nullable=True)
    op.drop_constraint(op.f('yasa_scan_tasks_project_id_fkey'), 'yasa_scan_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'yasa_scan_tasks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yasa_scan_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('yasa_scan_tasks_project_id_fkey'), 'yasa_scan_tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('yasa_scan_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='失败/中断错误信息',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'diagnostics_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='诊断日志摘要',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='扫描文件数',
               existing_server_default=sa.text('0'))
    op.alter_column('yasa_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='扫描耗时(毫秒)',
               existing_server_default=sa.text('0'))
    op.alter_column('yasa_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='发现总数',
               existing_server_default=sa.text('0'))
    op.alter_column('yasa_scan_tasks', 'rule_config_file',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='rule config 文件路径',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'checker_ids',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='逗号分隔 checker id',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'checker_pack_ids',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='逗号分隔 checker pack',
               existing_nullable=True)
    op.alter_column('yasa_scan_tasks', 'target_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='扫描目标路径',
               existing_nullable=False)
    op.alter_column('yasa_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='pending, running, completed, failed, interrupted',
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'yasa_findings', type_='foreignkey')
    op.create_foreign_key(op.f('yasa_findings_scan_task_id_fkey'), 'yasa_findings', 'yasa_scan_tasks', ['scan_task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('yasa_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='open, verified, false_positive, fixed',
               existing_server_default=sa.text("'open'::character varying"))
    op.create_index(op.f('ix_project_info_project_id'), 'project_info', ['project_id'], unique=False)
    op.alter_column('project_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_info', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='信息状态: pending, completed, failed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('project_info', 'description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='项目描述, 由大模型生成',
               existing_nullable=True)
    op.alter_column('project_info', 'language_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='项目所用编程语言信息, JSON格式',
               existing_nullable=True)
    op.alter_column('phpstan_rule_states', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='规则是否软删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('phpstan_rule_states', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='规则是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('phpstan_rule_states', 'rule_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='规则唯一键',
               existing_nullable=False)
    op.alter_column('opengrep_scan_tasks', 'lines_scanned',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'warning_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('opengrep_scan_tasks', 'rulesets',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='应用的规则集列表',
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('opengrep_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='pending, running, completed, failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('opengrep_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否启用',
               existing_server_default=sa.text('true'))
    op.alter_column('opengrep_rules', 'correct',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否是正确的语法',
               existing_server_default=sa.text('false'))
    op.alter_column('opengrep_rules', 'source',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='internal, patch, json',
               existing_nullable=False)
    op.alter_column('opengrep_rules', 'cwe',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='CWE列表，对应YAML中的cwe字段',
               existing_nullable=True)
    op.alter_column('opengrep_rules', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='规则描述，对应YAML中的message字段',
               existing_nullable=True)
    op.alter_column('opengrep_rules', 'confidence',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='置信度: HIGH, MEDIUM, LOW',
               existing_nullable=True)
    op.alter_column('opengrep_rules', 'severity',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ERROR, WARNING, INFO',
               existing_nullable=False)
    op.alter_column('opengrep_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='open, verified, false_positive',
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('opengrep_findings', 'severity',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ERROR, WARNING, INFO',
               existing_nullable=False)
    op.alter_column('opengrep_findings', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='漏洞描述',
               existing_nullable=True)
    op.alter_column('opengrep_findings', 'rule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('gitleaks_scan_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('gitleaks_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='已扫描文件数',
               existing_server_default=sa.text('0'))
    op.alter_column('gitleaks_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='扫描耗时(毫秒)',
               existing_server_default=sa.text('0'))
    op.alter_column('gitleaks_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='发现的密钥泄露总数',
               existing_server_default=sa.text('0'))
    op.alter_column('gitleaks_scan_tasks', 'no_git',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='是否不使用 git history',
               existing_server_default=sa.text("'true'::character varying"))
    op.alter_column('gitleaks_scan_tasks', 'target_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='扫描的目标路径',
               existing_nullable=False)
    op.alter_column('gitleaks_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='pending, running, completed, failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('gitleaks_rules', 'rule_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='gitleaks 规则 ID',
               existing_nullable=False)
    op.alter_column('gitleaks_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='open, verified, false_positive, fixed',
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('gitleaks_findings', 'fingerprint',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Gitleaks 指纹',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'date',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='日期 (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='邮箱 (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'author',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='作者 (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'commit',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Git commit SHA (如果有)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'match',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='匹配的完整文本',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'secret',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='密钥内容(已脱敏)',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'end_line',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='结束行号',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'start_line',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='起始行号',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'file_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='文件路径',
               existing_nullable=False)
    op.alter_column('gitleaks_findings', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='密钥描述',
               existing_nullable=True)
    op.alter_column('gitleaks_findings', 'rule_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='规则 ID (如 aws-access-token)',
               existing_nullable=False)
    op.alter_column('bandit_scan_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='失败/中断错误信息',
               existing_nullable=True)
    op.alter_column('bandit_scan_tasks', 'files_scanned',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='扫描文件数',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'scan_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='扫描耗时(毫秒)',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'low_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='LOW 严重度数量',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'medium_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='MEDIUM 严重度数量',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'high_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='HIGH 严重度数量',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='发现总数',
               existing_server_default=sa.text('0'))
    op.alter_column('bandit_scan_tasks', 'confidence_level',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='low, medium, high',
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('bandit_scan_tasks', 'severity_level',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='low, medium, high',
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('bandit_scan_tasks', 'target_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='扫描目标路径',
               existing_nullable=False)
    op.alter_column('bandit_scan_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='pending, running, completed, failed, interrupted',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bandit_rule_states', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='规则是否软删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('bandit_rule_states', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='规则是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('bandit_rule_states', 'test_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Bandit 规则ID，例如 B602',
               existing_nullable=False)
    op.drop_index('ix_bandit_findings_scan_task_status_created', table_name='bandit_findings')
    op.create_index(op.f('ix_bandit_findings_scan_task_status_created'), 'bandit_findings', ['scan_task_id', 'status', 'created_at'], unique=False)
    op.alter_column('bandit_findings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='open, verified, false_positive, fixed',
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('bandit_findings', 'issue_confidence',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='HIGH, MEDIUM, LOW',
               existing_nullable=False)
    op.alter_column('bandit_findings', 'issue_severity',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='HIGH, MEDIUM, LOW',
               existing_nullable=False)
    op.alter_column('bandit_findings', 'test_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Bandit 规则名称',
               existing_nullable=False)
    op.alter_column('bandit_findings', 'test_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Bandit 规则ID，例如 B602',
               existing_nullable=False)
    op.create_index(op.f('ix_agent_findings_reachability'), 'agent_findings', ['reachability'], unique=False)
    op.create_index(op.f('ix_agent_findings_confidence'), 'agent_findings', ['confidence'], unique=False)
    op.drop_table('project_management_metrics')
    # ### end Alembic commands ###






